class M{constructor(){this.mb=new ArrayBuffer(8192),this.mv=new DataView(this.mb),this.li=!1}g(s){if((s|=0)>4096||s<0)throw new Error;return this.mv.getUint16(2*s,this.li)}gd(s){return 4095&this.g(s)}gi(s){return 61440&this.g(s)}gsi(s){return this.gi(s)>>12}s(s,t){if(t|=0,(s|=0)>=4096||s<0)throw new Error;if(t>=65536||t<0)throw new Error;this.mv.setUint16(2*s,t,this.li)}sd(s,t){if(s|=0,(t|=0)>=4096||t<0)throw new Error;this.s(s,t|this.gi(s))}}class R{constructor(){this.value=0}g(){return 4095&this.value}s(s){s|=0,this.value=4095&s}i(s){s|=0,this.s(this.g()+s)}}class S{constructor(s){this.ss=0|s,this.s=new Uint16Array(this.ss),this.sp=0}o(){return 0==this.sp?0:(this.sp--,this.s[this.sp])}u(s){if(s|=0,this.sp++,this.sp>this.ss){this.sp=this.ss;for(let s=1;s<this.ss;s++)this.s[s-1]=this.s[s]}this.s[this.sp-1]=s}}const I=[s=>{s.f=2|s.f},s=>{},s=>{s.p.s(s.m.gd(s.p.g()))},s=>{1&s.f?s.p.s(4095&s.m.g(s.p.g())):s.p.i(1)},s=>{s.a.s(s.m.gd(s.m.gd(s.p.g()))),s.p.i(1)},s=>{s.m.sd(s.m.gd(s.p.g()),s.a.g()),s.p.i(1)},s=>{let t=s.m.gd(s.p.g()),i=12;for(;!(1<<i-1&t)&&i>0;i--);s.a.s(s.a.g()<<i)},s=>{let t=s.m.gd(s.p.g()),i=12;for(;!(1<<i-1&t)&&i>0;i--);s.a.s(s.a.g()>>i)},s=>{s.a.s(s.m.gd(s.p.g())^s.a.g()),s.p.i(1)},s=>{s.a.s(s.m.gd(s.p.g())&s.a.g()),s.p.i(1)},s=>{},s=>{s.a.s(s.a.g()+s.m.gd(s.p.g())),0==s.a.g()?s.f|=1:s.f&=2,s.p.i(1)},s=>{},s=>{s.a.s(s.s.o()),s.p.i(1)},s=>{s.s.u(s.a.g()),s.p.i(1)},s=>{s.p.i(1)}];class C{constructor(){this.m=new M,this.a=new R,this.p=new R,this.s=new S(12),this.f=0}t(){this.f&=1,I[this.m.gsi(this.p.g())].call(this,this)}r(){for(this.f&=1;!(2&this.f);)this.t()}}function ex(s){let t=new C,i=0;for(const h in s){const r=s[h];t.m.s(i++,r)}return t}
let mac = ex([0x2005,0xfff,0xf123,0xf002,0xf000,0x4002,0x5008,0x4004,0xb000,0x5004,0x4003,0xbfff,0x5003,0x3001,0x2007])
mac.r();
function dump(m){
    let r = [];
    let i = 2**12;
    while(i>0) if (m.m.g(--i) != 0) break;
    while(i>=0) r.push(m.m.g(i--).toString(16)); 
    return "[0x" + r.reverse().join(",0x") + "]"
  }
console.log(dump(mac))